### ISSUE TITLE
Axiom Theme not downloadable anymore

### ISSUE THREAD

**Issue by elisenlebkuch** [Jacksaur/Gorgeous-GRUB#7]
The Dropbox link on the pling.com site of the Axiom theme is broken. Could someone maybe send it to me?

**Comment by Jacksaur** [comment]
Appears that all of LegendaryBibo's Pling downloads have gone. I've tried to get in contact with him, hopefully he can reupload them somewhere.

**Comment by elisenlebkuch** [comment]
I've remade the theme as good as I can with [this theme](https://www.pling.com/p/1111552/) as base. If you want to host it, the theme is here: [Axiom.tar.gz](https://github.com/user-attachments/files/17193972/Axiom.tar.gz). Should I close the issue or leave it open in the case he responds? All of his other themes have the same problem too.
